// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/agents/[id]" | "/calendar" | "/events" | "/events/[id]" | "/integrations" | "/inventory" | "/invoices" | "/invoices/[id]" | "/labor" | "/login" | "/menu-performance" | "/menus" | "/recipes" | "/recipes/[id]" | "/sales" | "/settings" | "/team"
type AppRouteHandlerRoutes = "/api/auth/callback" | "/api/auth/demo" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/magic" | "/api/auth/session" | "/api/briefing/daily" | "/api/copilot" | "/api/settings" | "/api/settings-test" | "/api/slack/digest" | "/api/slack/events" | "/api/team"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/agents/[id]": { "id": string; }
  "/api/auth/callback": {}
  "/api/auth/demo": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/magic": {}
  "/api/auth/session": {}
  "/api/briefing/daily": {}
  "/api/copilot": {}
  "/api/settings": {}
  "/api/settings-test": {}
  "/api/slack/digest": {}
  "/api/slack/events": {}
  "/api/team": {}
  "/calendar": {}
  "/events": {}
  "/events/[id]": { "id": string; }
  "/integrations": {}
  "/inventory": {}
  "/invoices": {}
  "/invoices/[id]": { "id": string; }
  "/labor": {}
  "/login": {}
  "/menu-performance": {}
  "/menus": {}
  "/recipes": {}
  "/recipes/[id]": { "id": string; }
  "/sales": {}
  "/settings": {}
  "/team": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
